[package]
name = "swarm-host"
version = "0.1.0"
edition = "2021"

[dependencies]
array-bytes = "6.0.0"
async-trait = "0.1.64"
clap = { version = "4.1.4", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.2.2", features = ["derive"] }
fnv = "1.0.7"
futures = "0.3.25"
futures-timer = "3.0.2"
jsonrpsee = { version = "0.16.2", features = ["full"] }
libp2p = { version = "0.50.0", features = ["kad", "ping", "tokio", "identify", "noise", "request-response", "mdns", "dns", "mplex", "tcp", "websocket", "macros", "yamux"] }
pin-project = "1.0.12"
petgraph = "0.6.3"
rand = "0.8.5"
serde = { version = "1.0.152", features = ["derive"] }
serde_cbor = "0.11.2"
serde_json = "1.0.93"
smallvec = "1.10.0"
thiserror = "1.0.38"
tokio = { version = "1.23.0", features = ["full"] }
tokio-stream = "0.1.11"
tokio-util = "0.7.4"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["tracing-log", "env-filter"] }
void = "1.0.2"
sc-client-api = { version = "4.0.0-dev" }
sc-network-common = { version = "0.10.0-dev" }
sc-peerset = { version = "4.0.0-dev" }
sc-utils = { version = "4.0.0-dev" }
sp-core = { version = "7.0.0" }
sp-runtime = { version = "7.0.0" }
unsigned-varint = "0.7.1"
parking_lot = "0.12.1"
bytes = "1.4.0"
ip_network = "0.4.1"
asynchronous-codec = "0.6.1"
zeroize = "1.5.7"
