# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61pi.v1.proto\x12\x06\x61pi.v1\"\xb1\x01\n\x0c\x42lockRequest\x12\x0e\n\x06\x66ields\x18\x01 \x01(\r\x12\x0e\n\x04hash\x18\x02 \x01(\x0cH\x00\x12\x10\n\x06number\x18\x03 \x01(\x0cH\x00\x12$\n\tdirection\x18\x05 \x01(\x0e\x32\x11.api.v1.Direction\x12\x12\n\nmax_blocks\x18\x06 \x01(\r\x12\'\n\x1fsupport_multiple_justifications\x18\x07 \x01(\x08\x42\x0c\n\nfrom_block\"2\n\rBlockResponse\x12!\n\x06\x62locks\x18\x01 \x03(\x0b\x32\x11.api.v1.BlockData\"\xc4\x01\n\tBlockData\x12\x0c\n\x04hash\x18\x01 \x01(\x0c\x12\x0e\n\x06header\x18\x02 \x01(\x0c\x12\x0c\n\x04\x62ody\x18\x03 \x03(\x0c\x12\x0f\n\x07receipt\x18\x04 \x01(\x0c\x12\x15\n\rmessage_queue\x18\x05 \x01(\x0c\x12\x15\n\rjustification\x18\x06 \x01(\x0c\x12\x1e\n\x16is_empty_justification\x18\x07 \x01(\x08\x12\x16\n\x0ejustifications\x18\x08 \x01(\x0c\x12\x14\n\x0cindexed_body\x18\t \x03(\x0c\">\n\x0cStateRequest\x12\r\n\x05\x62lock\x18\x01 \x01(\x0c\x12\r\n\x05start\x18\x02 \x03(\x0c\x12\x10\n\x08no_proof\x18\x03 \x01(\x08\"K\n\rStateResponse\x12+\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1a.api.v1.KeyValueStateEntry\x12\r\n\x05proof\x18\x02 \x01(\x0c\"_\n\x12KeyValueStateEntry\x12\x12\n\nstate_root\x18\x01 \x01(\x0c\x12#\n\x07\x65ntries\x18\x02 \x03(\x0b\x32\x12.api.v1.StateEntry\x12\x10\n\x08\x63omplete\x18\x03 \x01(\x08\"(\n\nStateEntry\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x01(\x0c**\n\tDirection\x12\r\n\tAscending\x10\x00\x12\x0e\n\nDescending\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DIRECTION._serialized_start=735
  _DIRECTION._serialized_end=777
  _BLOCKREQUEST._serialized_start=25
  _BLOCKREQUEST._serialized_end=202
  _BLOCKRESPONSE._serialized_start=204
  _BLOCKRESPONSE._serialized_end=254
  _BLOCKDATA._serialized_start=257
  _BLOCKDATA._serialized_end=453
  _STATEREQUEST._serialized_start=455
  _STATEREQUEST._serialized_end=517
  _STATERESPONSE._serialized_start=519
  _STATERESPONSE._serialized_end=594
  _KEYVALUESTATEENTRY._serialized_start=596
  _KEYVALUESTATEENTRY._serialized_end=691
  _STATEENTRY._serialized_start=693
  _STATEENTRY._serialized_end=733
# @@protoc_insertion_point(module_scope)
